---
# tasks file for chrony

- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml

- name: Verify chronyd is installed
  ansible.builtin.package:
    name: "{{ chrony_packages }}"
    state: present
    update_cache: yes

- name: Edit chrony config file
  ansible.builtin.template:
    src: chrony.conf
    dest: "{{ chrony_etc_path }}/chrony.conf"
    mode: "{{ chrony_cfg_mode }}"
  notify:
    - Restart service

# Chronyd is not recommended for containers, it will cause errors
# So do not enable and run it
- name: Enable service
  ansible.builtin.service:
    name: "{{ chrony_service }}"
    state: started
    enabled: true
  when: ansible_virtualization_type not in _container_types
