---
- name: Validate chrony role inputs
  ansible.builtin.import_tasks: validate.yml
  tags:
    - chrony
    - validate

- name: Install chrony
  ansible.builtin.import_tasks: install.yml
  tags:
    - chrony
    - install

- name: Configure chrony
  ansible.builtin.import_tasks: config.yml
  tags:
    - chrony
    - config

- name: Manage chrony service
  ansible.builtin.import_tasks: service.yml
  tags:
    - chrony
    - service
