---
- name: Converge
  hosts: all
  vars:
    chrony_pools:
      - pool.ntp.org          iburst maxsources 4
      - ntp.ubuntu.com        iburst maxsources 4
      - 0.ubuntu.pool.ntp.org iburst maxsources 1
      - 1.ubuntu.pool.ntp.org iburst maxsources 1
      - 2.ubuntu.pool.ntp.org iburst maxsources 2
    chrony_driftfile: /var/lib/chrony/drift
    chrony_makestep: 1.0 3
    chrony_maxupdateskew: 100.0
    chrony_enable_rtcsync: true
    chrony_minsources: 2
    chrony_allow:
      - 192.168.0.0/16
    chrony_local: stratum 10
    chrony_keyfile: "{{ chrony_etc_path }}/chrony.keys"
    chrony_leapsecmode: slew
    chrony_logdir: /var/log/chrony
    chrony_log: measurements statistics tracking
    chrony_generic_settings:
      - { key: noclientlog }
      - { key: maxclockerror, value: 1 }
      - { key: inexistent, value: any, minversion: 999 }
      - { key: corrtimeratio, value: 3, minversion: 3 }

  pre_tasks:

    - name: Update Ubuntu/Debian systems cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_pkg_mgr == "apt"

    - name: pkg mgr
      ansible.builtin.debug:
        var: ansible_pkg_mgr

    - name: Install python3-dnf on Fedora systems
      ansible.builtin.raw: dnf install -y python3-dnf
      args:
        executable: /bin/bash
      changed_when: false
      when: ansible_pkg_mgr == "dnf5"

  roles:
    - role: guidugli.chrony
