---
ansible:
  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
        - --inventory=${MOLECULE_SCENARIO_DIRECTORY}/inventory/


  # Optional: pass environment variables to all ansible runs
  env:
    ANSIBLE_FORCE_COLOR: "true"

  # Optional: scenario-local ansible.cfg overrides (merged at runtime)
  cfg:
    defaults:
      host_key_checking: false
      retry_files_enabled: false
      interpreter_python: auto_silent
      stdout_callback: default
      callback_result_format: yaml


  # Playbooks are relative to THIS scenario directory
  playbooks:
    create: create.yml
    destroy: destroy.yml
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml

scenario:
  name: default
  test_sequence:
    - dependency
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy

dependency:
  name: galaxy
  options:
    requirements-file: ${MOLECULE_PROJECT_DIRECTORY}/requirements.yml

verifier:
  name: ansible
