---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: Check if configuration is ok
      ansible.builtin.command: chronyd -p
      changed_when: false
      register: chrony_result

    - name: Show output of chronyd -p command
      ansible.builtin.debug:
        msg: "{{ chrony_result }}"
