---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    chrony_manage_service: false
    chrony_pools:
      - pool.ntp.org iburst maxsources 4
    chrony_minsources: 1
    chrony_allow:
      - 192.168.0.0/16
    chrony_generic_settings:
      - key: noclientlog
      - key: corrtimeratio
        value: 3
        minversion: 3
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
